"""Report pipeline — generates reports from assessment data.

Supports multiple output formats: JSON, Markdown, HTML, and CSV.
Each format has a dedicated generator function that produces a structured
report with executive summary, findings, evidence, recommendations,
timeline, and appendix.
"""

from __future__ import annotations

import csv
import io
import json
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import Any

from app.core.logging import get_logger

logger = get_logger(__name__)


# ── Report Structure ───────────────────────────────────────────────


def build_report_data(
    assessment: dict[str, Any],
    findings: list[dict[str, Any]],
    evidence: list[dict[str, Any]],
    recommendations: list[dict[str, Any]] | None = None,
    timeline: list[dict[str, Any]] | None = None,
    statistics: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build a canonical report data structure.

    Args:
        assessment: Assessment data.
        findings: List of findings.
        evidence: List of evidence items.
        recommendations: Optional list of recommendations.
        timeline: Optional timeline events.
        statistics: Optional computed statistics.

    Returns:
        Complete report data dictionary.
    """
    severity_summary = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        sev = f.get("severity", "info")
        if sev in severity_summary:
            severity_summary[sev] += 1

    executive_summary = (
        f"Assessment '{assessment.get('name', 'Unknown')}' completed with "
        f"{len(findings)} finding(s) and {len(evidence)} evidence item(s). "
        f"Severity distribution: {severity_summary['critical']} critical, "
        f"{severity_summary['high']} high, {severity_summary['medium']} medium, "
        f"{severity_summary['low']} low, {severity_summary['info']} info."
    )

    return {
        "report_metadata": {
            "title": f"Assessment Report: {assessment.get('name', 'Unknown')}",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generator": "SecureScan Pro X Report Pipeline",
            "version": "1.0",
        },
        "executive_summary": executive_summary,
        "assessment": {
            "id": assessment.get("id"),
            "name": assessment.get("name"),
            "description": assessment.get("description"),
            "status": assessment.get("status"),
            "priority": assessment.get("priority"),
            "workspace_id": assessment.get("workspace_id"),
            "started_at": assessment.get("started_at"),
            "completed_at": assessment.get("completed_at"),
            "target_count": assessment.get("target_count", 0),
        },
        "findings": findings,
        "severity_summary": severity_summary,
        "evidence": evidence,
        "recommendations": recommendations or [],
        "timeline": timeline or [],
        "statistics": statistics or {},
        "appendix": {
            "tool_version": "0.1.0",
            "report_format_note": "Generated by SecureScan Pro X",
        },
    }


# ── Report Generators ──────────────────────────────────────────────


def generate_json_report(report_data: dict[str, Any]) -> str:
    """Generate a JSON report.

    Args:
        report_data: Canonical report data.

    Returns:
        JSON string.
    """
    return json.dumps(report_data, indent=2, default=str)


def generate_markdown_report(report_data: dict[str, Any]) -> str:
    """Generate a Markdown report.

    Args:
        report_data: Canonical report data.

    Returns:
        Markdown string.
    """
    lines: list[str] = []
    meta = report_data.get("report_metadata", {})
    assessment = report_data.get("assessment", {})
    severity = report_data.get("severity_summary", {})

    lines.append(f"# {meta.get('title', 'Assessment Report')}")
    lines.append("")
    lines.append(f"**Generated:** {meta.get('generated_at', 'N/A')}")
    lines.append(f"**Generator:** {meta.get('generator', 'N/A')}")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report_data.get("executive_summary", ""))
    lines.append("")

    lines.append("## Assessment Details")
    lines.append("")
    lines.append(f"- **ID:** {assessment.get('id', 'N/A')}")
    lines.append(f"- **Status:** {assessment.get('status', 'N/A')}")
    lines.append(f"- **Priority:** {assessment.get('priority', 'N/A')}")
    lines.append(f"- **Targets:** {assessment.get('target_count', 0)}")
    lines.append(f"- **Started:** {assessment.get('started_at', 'N/A')}")
    lines.append(f"- **Completed:** {assessment.get('completed_at', 'N/A')}")
    lines.append("")

    lines.append("## Severity Summary")
    lines.append("")
    for sev, count in severity.items():
        lines.append(f"- **{sev.upper()}:** {count}")
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    for i, finding in enumerate(report_data.get("findings", []), 1):
        lines.append(f"### {i}. {finding.get('title', 'Untitled')}")
        lines.append("")
        lines.append(f"- **Severity:** {finding.get('severity', 'N/A')}")
        lines.append(f"- **Category:** {finding.get('category', 'N/A')}")
        if finding.get("summary"):
            lines.append(f"- **Summary:** {finding['summary']}")
        if finding.get("recommendation"):
            lines.append(f"- **Recommendation:** {finding['recommendation']}")
        lines.append("")

    lines.append("## Evidence")
    lines.append("")
    for i, ev in enumerate(report_data.get("evidence", []), 1):
        lines.append(f"### {i}. {ev.get('title', 'Untitled')}")
        lines.append(f"- **Type:** {ev.get('evidence_type', 'N/A')}")
        lines.append(f"- **Source:** {ev.get('source', 'N/A')}")
        lines.append(f"- **Classification:** {ev.get('classification', 'N/A')}")
        lines.append("")

    if report_data.get("timeline"):
        lines.append("## Timeline")
        lines.append("")
        for event in report_data["timeline"]:
            lines.append(
                f"- [{event.get('timestamp', 'N/A')}] "
                f"{event.get('title', 'Event')}"
            )
        lines.append("")

    lines.append("## Appendix")
    lines.append("")
    appendix = report_data.get("appendix", {})
    lines.append(f"- **Tool Version:** {appendix.get('tool_version', 'N/A')}")
    lines.append(f"- **Note:** {appendix.get('report_format_note', '')}")

    return "\n".join(lines)


def generate_html_report(report_data: dict[str, Any]) -> str:
    """Generate an interactive HTML report.

    Args:
        report_data: Canonical report data.

    Returns:
        HTML string.
    """
    meta = report_data.get("report_metadata", {})
    assessment = report_data.get("assessment", {})
    severity = report_data.get("severity_summary", {})
    findings = report_data.get("findings", [])
    evidence = report_data.get("evidence", [])

    findings_rows = ""
    for f in findings:
        sev_class = f"sev-{f.get('severity', 'info')}"
        findings_rows += (
            f'<tr><td>{f.get("title", "")}</td>'
            f'<td class="{sev_class}">{f.get("severity", "")}</td>'
            f'<td>{f.get("category", "")}</td>'
            f'<td>{f.get("summary", "")}</td></tr>\n'
        )

    evidence_rows = ""
    for e in evidence:
        evidence_rows += (
            f'<tr><td>{e.get("title", "")}</td>'
            f'<td>{e.get("evidence_type", "")}</td>'
            f'<td>{e.get("source", "")}</td>'
            f'<td>{e.get("classification", "")}</td></tr>\n'
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{meta.get("title", "Assessment Report")}</title>
<style>
  :root {{ --bg: #0f172a; --fg: #e2e8f0; --card: #1e293b; --border: #334155;
           --primary: #3b82f6; --critical: #ef4444; --high: #f97316;
           --medium: #eab308; --low: #22c55e; --info: #3b82f6; }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: var(--bg);
          color: var(--fg); line-height: 1.6; padding: 2rem; }}
  .container {{ max-width: 1200px; margin: 0 auto; }}
  h1 {{ font-size: 2rem; margin-bottom: 0.5rem; }}
  h2 {{ font-size: 1.5rem; margin: 2rem 0 1rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
  .meta {{ color: #94a3b8; margin-bottom: 2rem; }}
  .summary {{ background: var(--card); padding: 1.5rem; border-radius: 8px; margin-bottom: 2rem; border-left: 4px solid var(--primary); }}
  .severity-bar {{ display: flex; gap: 1rem; margin: 1rem 0; flex-wrap: wrap; }}
  .severity-badge {{ padding: 0.5rem 1rem; border-radius: 6px; font-weight: 600; font-size: 0.875rem; }}
  .sev-critical {{ background: var(--critical); color: white; }}
  .sev-high {{ background: var(--high); color: white; }}
  .sev-medium {{ background: var(--medium); color: #1e293b; }}
  .sev-low {{ background: var(--low); color: #1e293b; }}
  .sev-info {{ background: var(--info); color: white; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid var(--border); }}
  th {{ background: var(--card); font-weight: 600; }}
  tr:hover {{ background: rgba(59, 130, 246, 0.05); }}
  .details {{ background: var(--card); padding: 1rem; border-radius: 8px; margin-bottom: 1rem; }}
  .details dt {{ font-weight: 600; display: inline; }}
  .details dd {{ display: inline; margin-left: 0.5rem; color: #94a3b8; }}
  .details dd::after {{ content: ''; display: block; }}
  footer {{ margin-top: 3rem; color: #64748b; font-size: 0.875rem; text-align: center; }}
</style>
</head>
<body>
<div class="container">
  <h1>{meta.get("title", "Assessment Report")}</h1>
  <div class="meta">
    Generated: {meta.get("generated_at", "N/A")} |
    Version: {meta.get("version", "N/A")}
  </div>

  <div class="summary">
    <strong>Executive Summary</strong>
    <p>{report_data.get("executive_summary", "")}</p>
  </div>

  <h2>Assessment Details</h2>
  <div class="details">
    <dl>
      <dt>ID</dt><dd>{assessment.get("id", "N/A")}</dd>
      <dt>Status</dt><dd>{assessment.get("status", "N/A")}</dd>
      <dt>Priority</dt><dd>{assessment.get("priority", "N/A")}</dd>
      <dt>Targets</dt><dd>{assessment.get("target_count", 0)}</dd>
      <dt>Started</dt><dd>{assessment.get("started_at", "N/A")}</dd>
      <dt>Completed</dt><dd>{assessment.get("completed_at", "N/A")}</dd>
    </dl>
  </div>

  <h2>Severity Distribution</h2>
  <div class="severity-bar">
    <span class="severity-badge sev-critical">CRITICAL: {severity.get("critical", 0)}</span>
    <span class="severity-badge sev-high">HIGH: {severity.get("high", 0)}</span>
    <span class="severity-badge sev-medium">MEDIUM: {severity.get("medium", 0)}</span>
    <span class="severity-badge sev-low">LOW: {severity.get("low", 0)}</span>
    <span class="severity-badge sev-info">INFO: {severity.get("info", 0)}</span>
  </div>

  <h2>Findings ({len(findings)})</h2>
  <table>
    <thead><tr><th>Title</th><th>Severity</th><th>Category</th><th>Summary</th></tr></thead>
    <tbody>{findings_rows}</tbody>
  </table>

  <h2>Evidence ({len(evidence)})</h2>
  <table>
    <thead><tr><th>Title</th><th>Type</th><th>Source</th><th>Classification</th></tr></thead>
    <tbody>{evidence_rows}</tbody>
  </table>

  <footer>
    <p>{report_data.get("appendix", {}).get("report_format_note", "")} |
       Tool Version: {report_data.get("appendix", {}).get("tool_version", "")}</p>
  </footer>
</div>
</body>
</html>"""
    return html


def generate_csv_report(report_data: dict[str, Any]) -> str:
    """Generate a CSV report (findings).

    Args:
        report_data: Canonical report data.

    Returns:
        CSV string.
    """
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow([
        "Title", "Severity", "Category", "Confidence", "Status",
        "Recommendation", "CVSS", "CWE IDs",
    ])

    for f in report_data.get("findings", []):
        writer.writerow([
            f.get("title", ""),
            f.get("severity", ""),
            f.get("category", ""),
            f.get("confidence", ""),
            f.get("status", ""),
            f.get("recommendation", ""),
            f.get("cvss_score", ""),
            ", ".join(f.get("cwe_ids", [])),
        ])

    return output.getvalue()


# ── Report Service Interface ──────────────────────────────────────


class ReportService(ABC):
    """Interface for report generation operations."""

    @abstractmethod
    async def generate(
        self,
        assessment_id: str,
        format: str = "json",
        assessment: dict[str, Any] | None = None,
        findings: list[dict[str, Any]] | None = None,
        evidence: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Generate a report in the specified format.

        Args:
            assessment_id: Assessment ID.
            format: Output format (json, markdown, html, csv).
            assessment: Assessment data.
            findings: List of findings.
            evidence: List of evidence items.

        Returns:
            Report metadata including content and path.
        """
        ...

    @abstractmethod
    async def list_reports(
        self,
        assessment_id: str,
    ) -> list[dict[str, Any]]:
        """List generated reports for an assessment.

        Args:
            assessment_id: Assessment ID.

        Returns:
            List of report metadata.
        """
        ...


# ── In-Memory Implementation ──────────────────────────────────────


class InMemoryReportService(ReportService):
    """In-memory report service for development and testing."""

    def __init__(self) -> None:
        """Initialize the report store."""
        self._reports: dict[str, list[dict[str, Any]]] = {}
        self._counter: int = 0

    async def generate(
        self,
        assessment_id: str,
        format: str = "json",
        assessment: dict[str, Any] | None = None,
        findings: list[dict[str, Any]] | None = None,
        evidence: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Generate a report.

        Args:
            assessment_id: Assessment ID.
            format: Output format.
            assessment: Assessment data.
            findings: Findings data.
            evidence: Evidence data.

        Returns:
            Report metadata with generated content.
        """
        report_data = build_report_data(
            assessment=assessment or {},
            findings=findings or [],
            evidence=evidence or [],
        )

        generators = {
            "json": generate_json_report,
            "markdown": generate_markdown_report,
            "html": generate_html_report,
            "csv": generate_csv_report,
        }

        generator = generators.get(format)
        if generator is None:
            raise ValueError(f"Unsupported report format: {format}")

        content = generator(report_data)

        self._counter += 1
        now = datetime.now(timezone.utc)
        report_id = f"report-{self._counter:08d}"

        import hashlib
        content_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()

        report = {
            "id": report_id,
            "assessment_id": assessment_id,
            "format": format,
            "title": report_data["report_metadata"]["title"],
            "content": content,
            "content_length": len(content),
            "integrity_hash": content_hash,
            "generated_at": now.isoformat(),
            "generated_by": "report_pipeline",
        }

        self._reports.setdefault(assessment_id, []).append(report)

        logger.info(
            "report.generated",
            report_id=report_id,
            assessment_id=assessment_id,
            format=format,
            content_length=len(content),
        )

        return dict(report)

    async def list_reports(
        self,
        assessment_id: str,
    ) -> list[dict[str, Any]]:
        """List reports for an assessment.

        Args:
            assessment_id: Assessment ID.

        Returns:
            List of report metadata (without content).
        """
        reports = self._reports.get(assessment_id, [])
        # Return metadata only (no content)
        return [
            {k: v for k, v in r.items() if k != "content"}
            for r in reports
        ]
